Red [
    Title: "Redlinks Logging Utilities"
    File: %logutils.red
    Version: "0.0.2"
    License: "MIT"
]

; -- Level wrappers & usage --
  comment {
   * #include %lib/logutils.red to use the logging utilities in your application
     * log levels are INFO, ERROR, WARNING, DEBUG, and SYSTEM
      - it is best practice to use the appropriate log level for each message, as this allows for better organization and filtering of log messages

  USAGE:
  * log-info "This is an info message"

    ; -- EXAMPLE USAGE --

     if empty? args [
        log-info "No command provided. Use 'help' for usage information."
    ]

  * log-error "This is an error message"
    - it is best practice to use the error log level for messages that are followed by a application exit 
     
    ; -- EXAMPLE USAGE --

     if not find links name [
        log-error ["Unknown command:" name]
        quit -->  this is an example of a situation where it is appropriate to use the error log level, because the application is exiting due to an error condition
    ]

  * log-warning "This is a warning message"
    - it is best practice to use the warning log level for messages that indicate a potential issue or something that may require attention but is not necessarily an error

    ; -- EXAMPLE USAGE --
    
    if empty? name [
        log-warning "No name provided. Using default name 'default'."
        name: "default" --> this is an example of a situation where it is appropriate to use the warning log level, because the application can continue to function but there is a potential issue that the user should be aware of
        ]

  * log-debug "This is a debug message"
    - it is best practice to use the debug log level for messages that are useful for debugging but not necessarily important for end users
    
    ; -- EXAMPLE USAGE --

     log-debug ["Received command:" name]

  * log-system "This is a system message" 
    - it is best practice to use the system log level for messages sent by the operating system or other external systems that are relevant to the application but not necessarily generated by the application itself

     ; -- EXAMPLE USAGE --

     log-system "System is running low on memory" 
}

; -- ANSI Color Values --
reset:     "^[[0m"
red:       "^[[31m"
green:     "^[[32m"
yellow:    "^[[33m"
blue:      "^[[34m"
gray:      "^[[90m"
purple:    "^[[35m"


log: func [level color msg] [
    print rejoin [
        color "[" level "] " reset msg
    ]
]

log-info: func [msg] [
    log "INFO" blue msg
]

log-error: func [msg] [
    log "ERROR" red msg
]

log-warning: func [msg] [
    log "WARNING" yellow msg
]

log-debug: func [msg] [
    log "DEBUG" green msg
]

log-system: func [msg] [
    log "SYSTEM" purple msg 
]
